version: '2'
services:
    jhipsterelasticsearchsampleapplication-app:
        image: jhipsterelasticsearchsampleapplication
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://jhipsterelasticsearchsampleapplication-mysql:3306/jhipsterelasticsearchsampleapplication?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=jhipsterelasticsearchsampleapplication-elasticsearch:9300
        ports:
            - 8080:8080
    jhipsterelasticsearchsampleapplication-mysql:
        extends:
            file: mysql.yml
            service: jhipsterelasticsearchsampleapplication-mysql
    jhipsterelasticsearchsampleapplication-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: jhipsterelasticsearchsampleapplication-elasticsearch
